fastlane_version "2.4.0"
default_platform :ios

before_all do
end

platform :ios do

  desc "Runs tests as iOS"
  lane :test do
    scan(
         scheme: "KabuKit",
         devices: ["iPhone 7"],
         clean: true,
         sdk: "iphonesimulator",
         output_types: "html"
         )
  end

end

